# Generated by Django 5.0.6 on 2024-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
